services:
  app:
    container_name: ${PROJECT_SUB_DOMAIN}
    build: .
    restart: unless-stopped
    env_file: .env
    logging:
        options:
            max-size: "10m"
            max-file: "3"
    networks:
      - proxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_SUB_DOMAIN}.entrypoints=websecure
      - traefik.http.routers.${PROJECT_SUB_DOMAIN}.rule=Host(`${PROJECT_SUB_DOMAIN}.${LOCAL_DOMAIN_NAME}`)
      - homepage.group=Personal
      - homepage.name=Text2Shop
      - homepage.icon=mdi-qrcode-edit
      - homepage.href=https://${PROJECT_SUB_DOMAIN}.${LOCAL_DOMAIN_NAME}
      - homepage.description=Paste text to transform it into a list. Useful for shopping 
networks:
    proxy:
        external: true
